### ISSUE TITLE
UI integration with ESLync seems be broken - "Searching" instead of load saved lrc

### ISSUE THREAD

**Issue by kyxap** [TT-ReBORN/Georgia-ReBORN#175]
It seems like there multiple issues with getting/reloading/saving/reading the lyrics but I will try to look into this one which is easy to reproduce:

After saving lrc file in the same folder and configuring plugin as such that next track play should skip the search and just load existing file.

Expected: file loaded, lrc displayed
Actual: UI shows search but seems like nothing happened, after some time UI shows that nothing was found

My config/reproduce steps:
<img width="1559" alt="image" src="https://github.com/TT-ReBORN/Georgia-ReBORN/assets/3080529/7aaf9768-b48c-4571-874e-87e09106d600">

If im tying to run manual search app see the file and can performer next searches no problem: 

<img width="967" alt="image" src="https://github.com/TT-ReBORN/Georgia-ReBORN/assets/3080529/2d0617f6-1070-4d4c-9f05-e99642cb3d0e">

**Comment by TT-ReBORN** [comment]
Hi @kyxap,

if you want to have a different directory and not the default, i.e 
`foobar2000\profile\cache\lyrics` ( `%fb2k_profile_path%cache\lyrics` )

you need to set it in the ESLyric directory location:
`foobar's Preferences` > `Tools` > `ESLyric` > `Lyric Option` > `Save settings`:
Location: Click on the `...` button and select `The same folder as the track` ( as shown in your screenshot ).

Now the lyrics will be auto saved and read from the album dir.
Additionally if needed, you can change the filename pattern in the ESLyric `Save settings` window
and in your `georgia-reborn-config.jsonc` config file:
`foobar2000\profile\georgia-reborn\configs\georgia-reborn-config.jsonc`
in the `"lyricsFilenamePatterns"` section.

HTH

-TT

**Comment by kyxap** [comment]
@TT-ReBORN 
hi, yeah I do have such configuration (safe file in local dir) that how I go that file in there. 

 After enabling auto search on playback seems  it started to work more stable but still im getting same issue occasionally. 

For example if I do those steps im getting this issue all the time
- open foobar2000
- click play (you must have some audio in playlist with local lyrics) 
- go to lyrics 

It will start to search and after some time gives:
<img width="313" alt="image" src="https://github.com/TT-ReBORN/Georgia-ReBORN/assets/3080529/67c598d1-86cf-4587-ae46-4f62b4a1242c">

if I do double click on the same song it opens saved lrc file... but again after some time (>1m) it will shows that no lyric found

Some something is not right, hope this make sense

**Comment by TT-ReBORN** [comment]
Ok, I have take a look and indeed there was an issue when using custom lyrics directories.
This should be now fixed in the latest DEV version, download and replace your files:
https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip

Thanks for reporting!

-TT

**Comment by kyxap** [comment]
apparently coping over master reset all my configs so it started to use cache folder which gave me false positive, after making all my changes back this issue is still there...

**Comment by TT-ReBORN** [comment]
> apparently coping over master reset all my configs so it started to use cache folder which gave me false positive, after making all my changes back this issue is still there...

---
You can make a theme backup that saves all your settings, here is how to do that:
01. Please make a theme backup via `Options > Settings > Theme backup > Make backup`.
02. Now make a new portable foobar install and install the latest DEV master version from here:
https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip
03. After you have downloaded and installed the theme, copy from your old foobar your theme backup folder:
`foobar2000_old\profile\backup`
to your new:
`foobar2000\profile\backup`
04. Now restore your theme backup via `Options > Settings > Theme backup > Restore backup`

---

> is there a manual how to debug that js and see what is wrong on my end?

To debug, you use the console.log and print the result in the console ( top menu View > Console ).

---

Can you please tell me the exact steps to reproduce?
Also can you post your modified lyrics settings and attach the lyric file that is making problems?

The default settings for the lyrics are as follows: 
The ESLyric download directory:
`%fb2k_profile_path%\cache\lyrics`

The ESLyric filename is:
`[%artist% - ]%title%` the brackets are optional, i.e when there is artist available, it will use `%artist% - %title%`
otherwise it will use just `%title%`.

The `"lyricsFilenamePatterns"` ( `tfilename` ) in your `georgia-reborn-config.jsonc` config file has these default patterns:
```
"%title%",
"%artist% - %title%",
"%artist% -%title%",
"%tracknumber% - %title%",
"%tracknumber% - %artist% - %title%"
```

**Comment by kyxap** [comment]
After looking into this I've found that my custom file naming of the lyrics is ignored and there no mechanism to look into saved file format. Here is not the best but potential solution https://github.com/TT-ReBORN/Georgia-ReBORN/pull/177

**Comment by TT-ReBORN** [comment]
I have tried your filename pattern and see no issues, it is working as expected.
It does apply and search for the user-set filename pattern from `"lyricsFilenamePatterns"` in your 
`georgia-reborn-config.jsonc config` file and is finding the lyrics:

![Custom Lyrics Filename Pattern](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/79368795/f0d6c1d3-5902-44d3-97ef-4e253f074ecb)

When deactivating `foobar's Preferences` > `Tools` > `ESLyric` > `Lyric Option` > `Lyric Search section` > `Automatically when playback starts` setting, it will not automatically fetch lyrics from the `ESLyric Lyric Sources` ( internet ) but then will try to find lyrics from the HDD/Tags ( offline ) using the `"lyricsFilenamePatterns"` in your `georgia-reborn-config.jsonc` config file.

So when using a custom lyric filename pattern, it should be set both in ESLyric `Save settings` 
and `"lyricsFilenamePatterns"` in your `georgia-reborn-config.jsonc` config file.

-TT

**Comment by kyxap** [comment]
oh manually set `lyricsFilenamePatterns`? yeah that will work, was not excepted such complexity :)

**Comment by kyxap** [comment]
btw I do have `georgia-reborn-config-3.0-DEV.jsonc` and also `georgia-reborn-config.jsonc` which one in used ? should I do any cleanup?

**Comment by TT-ReBORN** [comment]
The `georgia-reborn-config-3.0-DEV.jsonc` is a backup of the `georgia-reborn-config.jsonc` config file.
So the `georgia-reborn-config.jsonc` and `georgia-reborn-custom.jsonc` are the ones that are being used and read from.

The config backups will be created when the user has updated to a new Georgia-ReBORN version or 
when old/invalid config setting names or values were updated.

-TT
